id: resonator_flux
operation: resonator_flux
parameters:
  bias_step: 0.005
  bias_width: 0.4
  freq_step: 10000.0
  freq_width: 2000000.0
  nshots: 1000
  relaxation_time: 1000.0
targets:
- 0
update: true
