id: qubit_flux
operation: qubit_flux
parameters:
  bias_step: 0.0005
  bias_width: 0.1
  drive_amplitude: 0.005
  drive_duration: 4000
  freq_step: 100000.0
  freq_width: 15000000.0
  nshots: 500
  relaxation_time: 500
targets:
- 1
update: true
